CREATE TABLE hosts_entry(hosts_id INTEGER PRIMARY KEY, hosts_name VARCHAR(20), hosts_since DATE);
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(,'','');
INSERT INTO hosts_entry VALUES(6757,'Yuvraj','03 Dec 2012');
INSERT INTO hosts_entry VALUES(2567,'Harshit','02 Oct 2010');
INSERT INTO hosts_entry VALUES(2746,'Varun','17 Jul 2014');
INSERT INTO hosts_entry VALUES(3418,'Nitish','13 Jul 2012');
INSERT INTO hosts_entry VALUES(1723,'Tilak','18 May 2011');
INSERT INTO hosts_entry VALUES(7689,'Karan','24 Feb 2017');
INSERT INTO hosts_entry VALUES(2345,'Tarun','21 Jan 2012');
INSERT INTO hosts_entry VALUES(5467,'Chris','13 jul 2017');
INSERT INTO hosts_entry VALUES(1253,'Maxwell','14 Nov 2012');
INSERT INTO hosts_entry VALUES(4512,'Virender','03 Jun 2014');
INSERT INTO hosts_entry VALUES(5897,'Shivam','17 Feb 2012');
INSERT INTO hosts_entry VALUES(7856,'Aakash','24 Aug 2015');
INSERT INTO hosts_entry VALUES(9625,'Gagan','18 Sep 2018');
INSERT INTO hosts_entry VALUES(2687,'Umran','26 Oct 2019');
INSERT INTO hosts_entry VALUES(1320,'Rahul','13 Jul 2020');
INSERT INTO hosts_entry VALUES(4581,'Usman','19 May 2018');
INSERT INTO hosts_entry VALUES(7834,'Rohit','15 Dec 2016');
INSERT INTO hosts_entry VALUES(2525,'Virat','18 Dec 2016');
INSERT INTO hosts_entry VALUES(2617,'Arpan','29 Aug 2018');
INSERT INTO hosts_entry VALUES(2013,'Ranbir','12 Jun 2017');
INSERT INTO hosts_entry VALUES(2018,'Ranveer','26 Jan 2018');
INSERT INTO hosts_entry VALUES(1756,'Arjun','16 March 2013');
INSERT INTO hosts_entry VALUES(2526,'Karanveer','02 Oct 2012');
INSERT INTO hosts_entry VALUES(8796,'Rajeev','25 Sep 2010');
INSERT INTO hosts_entry VALUES(8123,'Danish','24 Nov 2015');
