CREATE TABLE Location_City(City_id INTEGER PRIMARY KEY,
 						   City VARCHAR(50),
					      State_id INTEGER, FOREIGN KEY(State_id) REFERENCES Location_State(State_id));

 INSERT INTO Location_City VALUES(1,'Patiala',21);
 INSERT INTO Location_City VALUES(2,'Mohali',21);
 INSERT INTO Location_City VALUES(3,'Ludhiana',21);
 INSERT INTO Location_City VALUES(4,'Bathinda',21);
 INSERT INTO Location_City VALUES(5,'Malerkotla',21);
 INSERT INTO Location_City VALUES(6,'Kapurthala',21);
 INSERT INTO Location_City VALUES(7,'Moga',21);
 INSERT INTO Location_City VALUES(8,'Pathankot',21);
 INSERT INTO Location_City VALUES(9,'Barnala',21);
 INSERT INTO Location_City VALUES(10,'Amritsar',21);
 INSERT INTO Location_City VALUES(11,'Batala',21);
 INSERT INTO Location_City VALUES(12,'Khanna',21);
 INSERT INTO Location_City VALUES(13,'Jalandhar',21);
 INSERT INTO Location_City VALUES(14,'Phagwara',21);
 INSERT INTO Location_City VALUES(15,'Hoshiarpur',21);
 INSERT INTO Location_City VALUES(16,'Firozpur',21);
 INSERT INTO Location_City VALUES(17,'Mansa',21);
 INSERT INTO Location_City VALUES(18,'Sangrur',21);
 INSERT INTO Location_City VALUES(19,'Zirakpur',21);
 INSERT INTO Location_City VALUES(20,'Mandi Gobindgarh',21);
 INSERT INTO Location_City VALUES(21,'Gurdaspur',21);
 INSERT INTO Location_City VALUES(22,'Tarn Taran Sahib',21);
 INSERT INTO Location_City VALUES(23,'Fazilka',21);
 INSERT INTO Location_City VALUES(24,'Jagraon',21);
 INSERT INTO Location_City VALUES(25,'Samana',21);
 INSERT INTO Location_City VALUES(26,'Anandpur Sahib',21);
 INSERT INTO Location_City VALUES(27,'Mukerian',21);
 INSERT INTO Location_City VALUES(28,'Majitha',21);
 INSERT INTO Location_City VALUES(29,'Sanaur',21);
 INSERT INTO Location_City VALUES(30,'Bassi Pathana',21);
 INSERT INTO Location_City VALUES(31,'Sri Muktsar Sahib',21);
 INSERT INTO Location_City VALUES(32,'Abohar',21);
 INSERT INTO Location_City VALUES(33,'Sahibzada Ajit Singh Nagar',21);
 INSERT INTO Location_City VALUES(34,'Rajpura',21);
 INSERT INTO Location_City VALUES(35,'Sunam',21);
 INSERT INTO Location_City VALUES(36,'Shaheed Bhagat Singh Nagar',21);
 INSERT INTO Location_City VALUES(37,'Kot Kapura',21);
 INSERT INTO Location_City VALUES(38,'Aur',21);
 INSERT INTO Location_City VALUES(39,'Malout',21);
 INSERT INTO Location_City VALUES(40,'Budhlada',21);
 INSERT INTO Location_City VALUES(41,'Nakodar',21);
 INSERT INTO Location_City VALUES(42,'Patti',21);
 INSERT INTO Location_City VALUES(43,'Zira',21);
 INSERT INTO Location_City VALUES(45,'Amloh',21);
 INSERT INTO Location_City VALUES(46,'Ajnala',21);
 INSERT INTO Location_City VALUES(47,'Shri Hargobindpur',21);
 INSERT INTO Location_City VALUES(48,'Balachaur',21);
 INSERT INTO Location_City VALUES(49,'Moonak',21);
 INSERT INTO Location_City VALUES(50,'Ghanaur',21);
