CREATE OR REPLACE TRIGGER HOST_UPDATE
AFTER UPDATE OF hosts_name ON hosts_entry FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('OLD NAME: ' ||:OLD.hosts_name);
DBMS_OUTPUT.PUT_LINE('NEW NAME:' ||:NEW.hosts_name);
EXCEPTION
WHEN NO_DATA_FOUND THEN
RAISE_APPLICATION_ERROR(-01403, 'No data found');
END;
