CREATE OR REPLACE TRIGGER SUNDAY
    BEFORE INSERT OR UPDATE OR DELETE ON AIRBNB
BEGIN
    IF RTRIM(UPPER(TO_CHAR(SYSDATE,'DAY')))='SUNDAY'
    THEN
    RAISE_APPLICATION_ERROR(-20022,'NO OPERARTION CAN BE PERFORMED ON SUNDAY');
END IF;
END;
;
